# Generated by Django 4.1.1 on 2022-09-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_theater',
            old_name='username',
            new_name='Username',
        ),
        migrations.AddField(
            model_name='operation_theater',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
