# Generated by Django 4.1.1 on 2022-09-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_username_operation_theater_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_theater',
            name='date',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='operation_theater',
            name='time',
            field=models.TimeField(max_length=50, null=True),
        ),
    ]
